### ISSUE TITLE
Types have been added to Biome

### ISSUE THREAD

**Issue by bookerthegeek** [AstroInteractive/Traverse#7] opened 2017-12-24 02:21 UTC
## Heyo! ##
Saw this in the console. Thought you would want to know about it. Looking forward to playing with the mod.

This did not cause a crash.
### Versions ###
 - Minecraft 1.12.2
 - forge-1.12.2-14.23.1.2575-universal.jar
 - traverse-1.12.1-1.3.1
### Revelant portion of the log ###
```
[16:58:53] [main/WARN] [FML]: No types have been added to Biome traverse:rocky_plateau, types have been assigned on a best-effort guess: [PLAINS]
```
[Complete Startup Log](https://gist.github.com/bookerthegeek/7bcce558a695d1784e0964914b0f14ab)

**Comment by TheCodedOne** [comment] 2017-12-24 02:22
duplicate of #6

**Closed by TheCodedOne** 2017-12-24 02:22 UTC
